# Generated by Django 4.2.2 on 2023-06-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
