# Generated by Django 4.2.2 on 2023-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
