# Generated by Django 4.2.2 on 2023-08-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_product_is_favorite"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="is_favorite",),
    ]
