# Generated by Django 4.2.2 on 2023-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment", name="rate", field=models.IntegerField(default=0),
        ),
    ]
