# Generated by Django 4.2.2 on 2023-07-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_product_rating"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="rating",),
        migrations.AddField(
            model_name="comment", name="rating", field=models.IntegerField(default=0),
        ),
    ]
