# Generated by Django 4.2.2 on 2023-07-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_bookuser_favorite_bookuser_favorite_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookuser", name="favorite_products",),
    ]
