# Generated by Django 4.2.2 on 2023-07-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_remove_bookuser_favorite_products"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="favorite", unique_together=None,),
        migrations.RemoveField(model_name="favorite", name="product",),
        migrations.RemoveField(model_name="favorite", name="user",),
        migrations.DeleteModel(name="BookUser",),
        migrations.DeleteModel(name="Favorite",),
    ]
